In [1]:
# univariate time series

from numpy import array



# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        
        # find the end of this pattern
        end_ix = i + n_steps
        
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
            
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
        
    return array(X), array(y)



# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]



# choose a number of time steps
n_steps = 3

# split into samples
X, y = split_sequence(raw_seq, n_steps)
X

y

# ACTUAL MLP TS MODEL



In [66]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import datetime

In [68]:

data = pd.read_csv('AirPassengers.csv')
data

Month  #Passengers
0    1949-01          112
1    1949-02          118
2    1949-03          132
3    1949-04          129
4    1949-05          121
..       ...          ...
139  1960-08          606
140  1960-09          508
141  1960-10          461
142  1960-11          390
143  1960-12          432

[144 rows x 2 columns]

In [69]:
data.Month = pd.to_datetime(data.Month)

In [70]:
dataset_ts=data.set_index("Month")

dataset_ts


#Passengers
Month                  
1949-01-01          112
1949-02-01          118
1949-03-01          132
1949-04-01          129
1949-05-01          121
...                 ...
1960-08-01          606
1960-09-01          508
1960-10-01          461
1960-11-01          390
1960-12-01          432

[144 rows x 1 columns]

In [83]:
ts1 = pd.concat(
    
    [dataset_ts.shift(3)["#Passengers"],dataset_ts.shift(2)["#Passengers"], 
     dataset_ts.shift(1)["#Passengers"],dataset_ts["#Passengers"]]
    ,axis=1
    )

ts1.columns=[["c1","c2","c3","target"]]

ts1


c1     c2     c3 target
Month                                 
1949-01-01    NaN    NaN    NaN    112
1949-02-01    NaN    NaN  112.0    118
1949-03-01    NaN  112.0  118.0    132
1949-04-01  112.0  118.0  132.0    129
1949-05-01  118.0  132.0  129.0    121
...           ...    ...    ...    ...
1960-08-01  472.0  535.0  622.0    606
1960-09-01  535.0  622.0  606.0    508
1960-10-01  622.0  606.0  508.0    461
1960-11-01  606.0  508.0  461.0    390
1960-12-01  508.0  461.0  390.0    432

[144 rows x 4 columns]

In [84]:
ts2 = ts1.dropna()

ts2

c1     c2     c3 target
Month                                 
1949-04-01  112.0  118.0  132.0    129
1949-05-01  118.0  132.0  129.0    121
1949-06-01  132.0  129.0  121.0    135
1949-07-01  129.0  121.0  135.0    148
1949-08-01  121.0  135.0  148.0    148
...           ...    ...    ...    ...
1960-08-01  472.0  535.0  622.0    606
1960-09-01  535.0  622.0  606.0    508
1960-10-01  622.0  606.0  508.0    461
1960-11-01  606.0  508.0  461.0    390
1960-12-01  508.0  461.0  390.0    432

[141 rows x 4 columns]

In [102]:
X = ts2[["c1","c2","c3"]].to_numpy()
X

array([[112., 118., 132.],
       [118., 132., 129.],
       [132., 129., 121.],
       [129., 121., 135.],
       [121., 135., 148.],
       [135., 148., 148.],
       [148., 148., 136.],
       [148., 136., 119.],
       [136., 119., 104.],
       [119., 104., 118.],
       [104., 118., 115.],
       [118., 115., 126.],
       [115., 126., 141.],
       [126., 141., 135.],
       [141., 135., 125.],
       [135., 125., 149.],
       [125., 149., 170.],
       [149., 170., 170.],
       [170., 170., 158.],
       [170., 158., 133.],
       [158., 133., 114.],
       [133., 114., 140.],
       [114., 140., 145.],
       [140., 145., 150.],
       [145., 150., 178.],
       [150., 178., 163.],
       [178., 163., 172.],
       [163., 172., 178.],
       [172., 178., 199.],
       [178., 199., 199.],
       [199., 199., 184.],
       [199., 184., 162.],
       [184., 162., 146.],
       [162., 146., 166.],
       [146., 166., 171.],
       [166., 171., 180.],
       [171., 180., 193.],
 

In [107]:
y= ts2[["target"]].to_numpy()
y

array([[129],
       [121],
       [135],
       [148],
       [148],
       [136],
       [119],
       [104],
       [118],
       [115],
       [126],
       [141],
       [135],
       [125],
       [149],
       [170],
       [170],
       [158],
       [133],
       [114],
       [140],
       [145],
       [150],
       [178],
       [163],
       [172],
       [178],
       [199],
       [199],
       [184],
       [162],
       [146],
       [166],
       [171],
       [180],
       [193],
       [181],
       [183],
       [218],
       [230],
       [242],
       [209],
       [191],
       [172],
       [194],
       [196],
       [196],
       [236],
       [235],
       [229],
       [243],
       [264],
       [272],
       [237],
       [211],
       [180],
       [201],
       [204],
       [188],
       [235],
       [227],
       [234],
       [264],
       [302],
       [293],
       [259],
       [229],
       [203],
       [229],
       [242],
       [233],
      

In [95]:
y = y.flatten()
y

array([129, 121, 135, 148, 148, 136, 119, 104, 118, 115, 126, 141, 135,
       125, 149, 170, 170, 158, 133, 114, 140, 145, 150, 178, 163, 172,
       178, 199, 199, 184, 162, 146, 166, 171, 180, 193, 181, 183, 218,
       230, 242, 209, 191, 172, 194, 196, 196, 236, 235, 229, 243, 264,
       272, 237, 211, 180, 201, 204, 188, 235, 227, 234, 264, 302, 293,
       259, 229, 203, 229, 242, 233, 267, 269, 270, 315, 364, 347, 312,
       274, 237, 278, 284, 277, 317, 313, 318, 374, 413, 405, 355, 306,
       271, 306, 315, 301, 356, 348, 355, 422, 465, 467, 404, 347, 305,
       336, 340, 318, 362, 348, 363, 435, 491, 505, 404, 359, 310, 337,
       360, 342, 406, 396, 420, 472, 548, 559, 463, 407, 362, 405, 417,
       391, 419, 461, 472, 535, 622, 606, 508, 461, 390, 432], dtype=int64)

In [96]:

from keras.models import Sequential
from keras.layers import Dense


In [114]:

# define model
model = Sequential()

model.add(Dense(10, 
                activation='relu', 
                input_dim=3))

model.add(Dense(1))

model.compile(optimizer='adam', 
              loss='mse')

In [121]:
model.layers[0].activation

<function keras.activations.relu(x, alpha=0.0, max_value=None, threshold=0.0)>

In [122]:
model.layers[1].activation

<function keras.activations.linear(x)>

In [137]:
??model.fit

In [123]:

# fit model

model.fit(X, y, 
          epochs=2000, 
          
          verbose=2)


Epoch 1/2000
1/1 - 0s - loss: 3236.4121 - 436ms/epoch - 436ms/step
Epoch 2/2000
1/1 - 0s - loss: 3197.2512 - 3ms/epoch - 3ms/step
Epoch 3/2000
1/1 - 0s - loss: 3158.2605 - 10ms/epoch - 10ms/step
Epoch 4/2000
1/1 - 0s - loss: 3119.4436 - 12ms/epoch - 12ms/step
Epoch 5/2000
1/1 - 0s - loss: 3080.8049 - 14ms/epoch - 14ms/step
Epoch 6/2000
1/1 - 0s - loss: 3042.3066 - 15ms/epoch - 15ms/step
Epoch 7/2000
1/1 - 0s - loss: 3003.9856 - 12ms/epoch - 12ms/step
Epoch 8/2000
1/1 - 0s - loss: 2965.8469 - 7ms/epoch - 7ms/step
Epoch 9/2000
1/1 - 0s - loss: 2927.8945 - 9ms/epoch - 9ms/step
Epoch 10/2000
1/1 - 0s - loss: 2890.1311 - 8ms/epoch - 8ms/step
Epoch 11/2000
1/1 - 0s - loss: 2852.5603 - 13ms/epoch - 13ms/step
Epoch 12/2000
1/1 - 0s - loss: 2815.1846 - 13ms/epoch - 13ms/step
Epoch 13/2000
1/1 - 0s - loss: 2777.9592 - 14ms/epoch - 14ms/step
Epoch 14/2000
1/1 - 0s - loss: 2740.9226 - 24ms/epoch - 24ms/step
Epoch 15/2000
1/1 - 0s - loss: 2704.0830 - 9ms/epoch - 9ms/step
Epoch 16/2000
1/1 - 0s - lo

Epoch 128/2000
1/1 - 0s - loss: 173.6331 - 9ms/epoch - 9ms/step
Epoch 129/2000
1/1 - 0s - loss: 167.2772 - 6ms/epoch - 6ms/step
Epoch 130/2000
1/1 - 0s - loss: 161.1430 - 6ms/epoch - 6ms/step
Epoch 131/2000
1/1 - 0s - loss: 155.2261 - 12ms/epoch - 12ms/step
Epoch 132/2000
1/1 - 0s - loss: 149.5220 - 9ms/epoch - 9ms/step
Epoch 133/2000
1/1 - 0s - loss: 144.0260 - 7ms/epoch - 7ms/step
Epoch 134/2000
1/1 - 0s - loss: 138.7337 - 6ms/epoch - 6ms/step
Epoch 135/2000
1/1 - 0s - loss: 133.6405 - 8ms/epoch - 8ms/step
Epoch 136/2000
1/1 - 0s - loss: 128.7418 - 6ms/epoch - 6ms/step
Epoch 137/2000
1/1 - 0s - loss: 124.0328 - 4ms/epoch - 4ms/step
Epoch 138/2000
1/1 - 0s - loss: 119.5090 - 5ms/epoch - 5ms/step
Epoch 139/2000
1/1 - 0s - loss: 115.1658 - 5ms/epoch - 5ms/step
Epoch 140/2000
1/1 - 0s - loss: 110.9984 - 5ms/epoch - 5ms/step
Epoch 141/2000
1/1 - 0s - loss: 107.0022 - 8ms/epoch - 8ms/step
Epoch 142/2000
1/1 - 0s - loss: 103.1726 - 9ms/epoch - 9ms/step
Epoch 143/2000
1/1 - 0s - loss: 99.504

Epoch 257/2000
1/1 - 0s - loss: 32.9239 - 4ms/epoch - 4ms/step
Epoch 258/2000
1/1 - 0s - loss: 32.9056 - 7ms/epoch - 7ms/step
Epoch 259/2000
1/1 - 0s - loss: 32.8872 - 4ms/epoch - 4ms/step
Epoch 260/2000
1/1 - 0s - loss: 32.8688 - 10ms/epoch - 10ms/step
Epoch 261/2000
1/1 - 0s - loss: 32.8504 - 5ms/epoch - 5ms/step
Epoch 262/2000
1/1 - 0s - loss: 32.8320 - 7ms/epoch - 7ms/step
Epoch 263/2000
1/1 - 0s - loss: 32.8135 - 5ms/epoch - 5ms/step
Epoch 264/2000
1/1 - 0s - loss: 32.7950 - 6ms/epoch - 6ms/step
Epoch 265/2000
1/1 - 0s - loss: 32.7765 - 7ms/epoch - 7ms/step
Epoch 266/2000
1/1 - 0s - loss: 32.7580 - 6ms/epoch - 6ms/step
Epoch 267/2000
1/1 - 0s - loss: 32.7394 - 4ms/epoch - 4ms/step
Epoch 268/2000
1/1 - 0s - loss: 32.7208 - 8ms/epoch - 8ms/step
Epoch 269/2000
1/1 - 0s - loss: 32.7021 - 11ms/epoch - 11ms/step
Epoch 270/2000
1/1 - 0s - loss: 32.6835 - 7ms/epoch - 7ms/step
Epoch 271/2000
1/1 - 0s - loss: 32.6648 - 5ms/epoch - 5ms/step
Epoch 272/2000
1/1 - 0s - loss: 32.6460 - 7ms/epoch

1/1 - 0s - loss: 30.3402 - 7ms/epoch - 7ms/step
Epoch 387/2000
1/1 - 0s - loss: 30.3187 - 8ms/epoch - 8ms/step
Epoch 388/2000
1/1 - 0s - loss: 30.2971 - 6ms/epoch - 6ms/step
Epoch 389/2000
1/1 - 0s - loss: 30.2755 - 6ms/epoch - 6ms/step
Epoch 390/2000
1/1 - 0s - loss: 30.2540 - 8ms/epoch - 8ms/step
Epoch 391/2000
1/1 - 0s - loss: 30.2324 - 4ms/epoch - 4ms/step
Epoch 392/2000
1/1 - 0s - loss: 30.2107 - 23ms/epoch - 23ms/step
Epoch 393/2000
1/1 - 0s - loss: 30.1891 - 6ms/epoch - 6ms/step
Epoch 394/2000
1/1 - 0s - loss: 30.1674 - 5ms/epoch - 5ms/step
Epoch 395/2000
1/1 - 0s - loss: 30.1457 - 8ms/epoch - 8ms/step
Epoch 396/2000
1/1 - 0s - loss: 30.1240 - 7ms/epoch - 7ms/step
Epoch 397/2000
1/1 - 0s - loss: 30.1023 - 4ms/epoch - 4ms/step
Epoch 398/2000
1/1 - 0s - loss: 30.0806 - 7ms/epoch - 7ms/step
Epoch 399/2000
1/1 - 0s - loss: 30.0589 - 5ms/epoch - 5ms/step
Epoch 400/2000
1/1 - 0s - loss: 30.0370 - 16ms/epoch - 16ms/step
Epoch 401/2000
1/1 - 0s - loss: 30.0153 - 6ms/epoch - 6ms/step
Epo

Epoch 516/2000
1/1 - 0s - loss: 27.5233 - 8ms/epoch - 8ms/step
Epoch 517/2000
1/1 - 0s - loss: 27.5068 - 4ms/epoch - 4ms/step
Epoch 518/2000
1/1 - 0s - loss: 27.4904 - 4ms/epoch - 4ms/step
Epoch 519/2000
1/1 - 0s - loss: 27.4739 - 5ms/epoch - 5ms/step
Epoch 520/2000
1/1 - 0s - loss: 27.4575 - 5ms/epoch - 5ms/step
Epoch 521/2000
1/1 - 0s - loss: 27.4411 - 5ms/epoch - 5ms/step
Epoch 522/2000
1/1 - 0s - loss: 27.4247 - 6ms/epoch - 6ms/step
Epoch 523/2000
1/1 - 0s - loss: 27.4083 - 3ms/epoch - 3ms/step
Epoch 524/2000
1/1 - 0s - loss: 27.3920 - 8ms/epoch - 8ms/step
Epoch 525/2000
1/1 - 0s - loss: 27.3756 - 11ms/epoch - 11ms/step
Epoch 526/2000
1/1 - 0s - loss: 27.3592 - 11ms/epoch - 11ms/step
Epoch 527/2000
1/1 - 0s - loss: 27.3428 - 6ms/epoch - 6ms/step
Epoch 528/2000
1/1 - 0s - loss: 27.3265 - 3ms/epoch - 3ms/step
Epoch 529/2000
1/1 - 0s - loss: 27.3101 - 5ms/epoch - 5ms/step
Epoch 530/2000
1/1 - 0s - loss: 27.2938 - 4ms/epoch - 4ms/step
Epoch 531/2000
1/1 - 0s - loss: 27.2774 - 9ms/epoch

Epoch 646/2000
1/1 - 0s - loss: 25.3405 - 4ms/epoch - 4ms/step
Epoch 647/2000
1/1 - 0s - loss: 25.3232 - 5ms/epoch - 5ms/step
Epoch 648/2000
1/1 - 0s - loss: 25.3059 - 5ms/epoch - 5ms/step
Epoch 649/2000
1/1 - 0s - loss: 25.2885 - 6ms/epoch - 6ms/step
Epoch 650/2000
1/1 - 0s - loss: 25.2712 - 8ms/epoch - 8ms/step
Epoch 651/2000
1/1 - 0s - loss: 25.2538 - 8ms/epoch - 8ms/step
Epoch 652/2000
1/1 - 0s - loss: 25.2365 - 4ms/epoch - 4ms/step
Epoch 653/2000
1/1 - 0s - loss: 25.2191 - 8ms/epoch - 8ms/step
Epoch 654/2000
1/1 - 0s - loss: 25.2017 - 4ms/epoch - 4ms/step
Epoch 655/2000
1/1 - 0s - loss: 25.1843 - 7ms/epoch - 7ms/step
Epoch 656/2000
1/1 - 0s - loss: 25.1669 - 5ms/epoch - 5ms/step
Epoch 657/2000
1/1 - 0s - loss: 25.1495 - 8ms/epoch - 8ms/step
Epoch 658/2000
1/1 - 0s - loss: 25.1321 - 10ms/epoch - 10ms/step
Epoch 659/2000
1/1 - 0s - loss: 25.1147 - 6ms/epoch - 6ms/step
Epoch 660/2000
1/1 - 0s - loss: 25.0973 - 8ms/epoch - 8ms/step
Epoch 661/2000
1/1 - 0s - loss: 25.0799 - 6ms/epoch -

Epoch 776/2000
1/1 - 0s - loss: 23.0352 - 9ms/epoch - 9ms/step
Epoch 777/2000
1/1 - 0s - loss: 23.0171 - 4ms/epoch - 4ms/step
Epoch 778/2000
1/1 - 0s - loss: 22.9990 - 4ms/epoch - 4ms/step
Epoch 779/2000
1/1 - 0s - loss: 22.9809 - 9ms/epoch - 9ms/step
Epoch 780/2000
1/1 - 0s - loss: 22.9629 - 5ms/epoch - 5ms/step
Epoch 781/2000
1/1 - 0s - loss: 22.9448 - 5ms/epoch - 5ms/step
Epoch 782/2000
1/1 - 0s - loss: 22.9267 - 6ms/epoch - 6ms/step
Epoch 783/2000
1/1 - 0s - loss: 22.9086 - 4ms/epoch - 4ms/step
Epoch 784/2000
1/1 - 0s - loss: 22.8905 - 7ms/epoch - 7ms/step
Epoch 785/2000
1/1 - 0s - loss: 22.8723 - 5ms/epoch - 5ms/step
Epoch 786/2000
1/1 - 0s - loss: 22.8542 - 5ms/epoch - 5ms/step
Epoch 787/2000
1/1 - 0s - loss: 22.8361 - 7ms/epoch - 7ms/step
Epoch 788/2000
1/1 - 0s - loss: 22.8180 - 7ms/epoch - 7ms/step
Epoch 789/2000
1/1 - 0s - loss: 22.7999 - 4ms/epoch - 4ms/step
Epoch 790/2000
1/1 - 0s - loss: 22.7817 - 4ms/epoch - 4ms/step
Epoch 791/2000
1/1 - 0s - loss: 22.7636 - 4ms/epoch - 4

Epoch 906/2000
1/1 - 0s - loss: 20.6577 - 5ms/epoch - 5ms/step
Epoch 907/2000
1/1 - 0s - loss: 20.6393 - 8ms/epoch - 8ms/step
Epoch 908/2000
1/1 - 0s - loss: 20.6208 - 4ms/epoch - 4ms/step
Epoch 909/2000
1/1 - 0s - loss: 20.6024 - 6ms/epoch - 6ms/step
Epoch 910/2000
1/1 - 0s - loss: 20.5839 - 4ms/epoch - 4ms/step
Epoch 911/2000
1/1 - 0s - loss: 20.5654 - 4ms/epoch - 4ms/step
Epoch 912/2000
1/1 - 0s - loss: 20.5470 - 10ms/epoch - 10ms/step
Epoch 913/2000
1/1 - 0s - loss: 20.5286 - 4ms/epoch - 4ms/step
Epoch 914/2000
1/1 - 0s - loss: 20.5101 - 4ms/epoch - 4ms/step
Epoch 915/2000
1/1 - 0s - loss: 20.4917 - 8ms/epoch - 8ms/step
Epoch 916/2000
1/1 - 0s - loss: 20.4732 - 7ms/epoch - 7ms/step
Epoch 917/2000
1/1 - 0s - loss: 20.4548 - 5ms/epoch - 5ms/step
Epoch 918/2000
1/1 - 0s - loss: 20.4363 - 5ms/epoch - 5ms/step
Epoch 919/2000
1/1 - 0s - loss: 20.4179 - 5ms/epoch - 5ms/step
Epoch 920/2000
1/1 - 0s - loss: 20.3994 - 8ms/epoch - 8ms/step
Epoch 921/2000
1/1 - 0s - loss: 20.3809 - 5ms/epoch -

1/1 - 0s - loss: 18.2753 - 7ms/epoch - 7ms/step
Epoch 1036/2000
1/1 - 0s - loss: 18.2569 - 4ms/epoch - 4ms/step
Epoch 1037/2000
1/1 - 0s - loss: 18.2384 - 6ms/epoch - 6ms/step
Epoch 1038/2000
1/1 - 0s - loss: 18.2200 - 4ms/epoch - 4ms/step
Epoch 1039/2000
1/1 - 0s - loss: 18.2016 - 5ms/epoch - 5ms/step
Epoch 1040/2000
1/1 - 0s - loss: 18.1832 - 5ms/epoch - 5ms/step
Epoch 1041/2000
1/1 - 0s - loss: 18.1647 - 5ms/epoch - 5ms/step
Epoch 1042/2000
1/1 - 0s - loss: 18.1463 - 4ms/epoch - 4ms/step
Epoch 1043/2000
1/1 - 0s - loss: 18.1278 - 8ms/epoch - 8ms/step
Epoch 1044/2000
1/1 - 0s - loss: 18.1094 - 9ms/epoch - 9ms/step
Epoch 1045/2000
1/1 - 0s - loss: 18.0910 - 12ms/epoch - 12ms/step
Epoch 1046/2000
1/1 - 0s - loss: 18.0726 - 6ms/epoch - 6ms/step
Epoch 1047/2000
1/1 - 0s - loss: 18.0541 - 3ms/epoch - 3ms/step
Epoch 1048/2000
1/1 - 0s - loss: 18.0357 - 5ms/epoch - 5ms/step
Epoch 1049/2000
1/1 - 0s - loss: 18.0173 - 6ms/epoch - 6ms/step
Epoch 1050/2000
1/1 - 0s - loss: 17.9989 - 4ms/epoch -

Epoch 1163/2000
1/1 - 0s - loss: 15.9335 - 5ms/epoch - 5ms/step
Epoch 1164/2000
1/1 - 0s - loss: 15.9154 - 6ms/epoch - 6ms/step
Epoch 1165/2000
1/1 - 0s - loss: 15.8973 - 7ms/epoch - 7ms/step
Epoch 1166/2000
1/1 - 0s - loss: 15.8792 - 5ms/epoch - 5ms/step
Epoch 1167/2000
1/1 - 0s - loss: 15.8611 - 4ms/epoch - 4ms/step
Epoch 1168/2000
1/1 - 0s - loss: 15.8430 - 6ms/epoch - 6ms/step
Epoch 1169/2000
1/1 - 0s - loss: 15.8250 - 5ms/epoch - 5ms/step
Epoch 1170/2000
1/1 - 0s - loss: 15.8069 - 6ms/epoch - 6ms/step
Epoch 1171/2000
1/1 - 0s - loss: 15.7888 - 5ms/epoch - 5ms/step
Epoch 1172/2000
1/1 - 0s - loss: 15.7708 - 11ms/epoch - 11ms/step
Epoch 1173/2000
1/1 - 0s - loss: 15.7527 - 11ms/epoch - 11ms/step
Epoch 1174/2000
1/1 - 0s - loss: 15.7347 - 4ms/epoch - 4ms/step
Epoch 1175/2000
1/1 - 0s - loss: 15.7166 - 10ms/epoch - 10ms/step
Epoch 1176/2000
1/1 - 0s - loss: 15.6986 - 4ms/epoch - 4ms/step
Epoch 1177/2000
1/1 - 0s - loss: 15.6805 - 6ms/epoch - 6ms/step
Epoch 1178/2000
1/1 - 0s - loss: 1

Epoch 1291/2000
1/1 - 0s - loss: 13.6568 - 8ms/epoch - 8ms/step
Epoch 1292/2000
1/1 - 0s - loss: 13.6394 - 8ms/epoch - 8ms/step
Epoch 1293/2000
1/1 - 0s - loss: 13.6220 - 5ms/epoch - 5ms/step
Epoch 1294/2000
1/1 - 0s - loss: 13.6046 - 4ms/epoch - 4ms/step
Epoch 1295/2000
1/1 - 0s - loss: 13.5872 - 6ms/epoch - 6ms/step
Epoch 1296/2000
1/1 - 0s - loss: 13.5698 - 6ms/epoch - 6ms/step
Epoch 1297/2000
1/1 - 0s - loss: 13.5524 - 6ms/epoch - 6ms/step
Epoch 1298/2000
1/1 - 0s - loss: 13.5350 - 5ms/epoch - 5ms/step
Epoch 1299/2000
1/1 - 0s - loss: 13.5177 - 6ms/epoch - 6ms/step
Epoch 1300/2000
1/1 - 0s - loss: 13.5003 - 5ms/epoch - 5ms/step
Epoch 1301/2000
1/1 - 0s - loss: 13.4829 - 9ms/epoch - 9ms/step
Epoch 1302/2000
1/1 - 0s - loss: 13.4656 - 9ms/epoch - 9ms/step
Epoch 1303/2000
1/1 - 0s - loss: 13.4482 - 5ms/epoch - 5ms/step
Epoch 1304/2000
1/1 - 0s - loss: 13.4309 - 5ms/epoch - 5ms/step
Epoch 1305/2000
1/1 - 0s - loss: 13.4135 - 7ms/epoch - 7ms/step
Epoch 1306/2000
1/1 - 0s - loss: 13.3962

Epoch 1419/2000
1/1 - 0s - loss: 11.4873 - 6ms/epoch - 6ms/step
Epoch 1420/2000
1/1 - 0s - loss: 11.4709 - 9ms/epoch - 9ms/step
Epoch 1421/2000
1/1 - 0s - loss: 11.4545 - 6ms/epoch - 6ms/step
Epoch 1422/2000
1/1 - 0s - loss: 11.4381 - 6ms/epoch - 6ms/step
Epoch 1423/2000
1/1 - 0s - loss: 11.4217 - 5ms/epoch - 5ms/step
Epoch 1424/2000
1/1 - 0s - loss: 11.4053 - 4ms/epoch - 4ms/step
Epoch 1425/2000
1/1 - 0s - loss: 11.3889 - 4ms/epoch - 4ms/step
Epoch 1426/2000
1/1 - 0s - loss: 11.3726 - 3ms/epoch - 3ms/step
Epoch 1427/2000
1/1 - 0s - loss: 11.3562 - 4ms/epoch - 4ms/step
Epoch 1428/2000
1/1 - 0s - loss: 11.3399 - 3ms/epoch - 3ms/step
Epoch 1429/2000
1/1 - 0s - loss: 11.3235 - 4ms/epoch - 4ms/step
Epoch 1430/2000
1/1 - 0s - loss: 11.3072 - 4ms/epoch - 4ms/step
Epoch 1431/2000
1/1 - 0s - loss: 11.2909 - 8ms/epoch - 8ms/step
Epoch 1432/2000
1/1 - 0s - loss: 11.2745 - 7ms/epoch - 7ms/step
Epoch 1433/2000
1/1 - 0s - loss: 11.2582 - 12ms/epoch - 12ms/step
Epoch 1434/2000
1/1 - 0s - loss: 11.24

1/1 - 0s - loss: 9.6714 - 4ms/epoch - 4ms/step
Epoch 1548/2000
1/1 - 0s - loss: 9.6584 - 4ms/epoch - 4ms/step
Epoch 1549/2000
1/1 - 0s - loss: 9.6454 - 6ms/epoch - 6ms/step
Epoch 1550/2000
1/1 - 0s - loss: 9.6323 - 6ms/epoch - 6ms/step
Epoch 1551/2000
1/1 - 0s - loss: 9.6193 - 5ms/epoch - 5ms/step
Epoch 1552/2000
1/1 - 0s - loss: 9.6063 - 4ms/epoch - 4ms/step
Epoch 1553/2000
1/1 - 0s - loss: 9.5933 - 10ms/epoch - 10ms/step
Epoch 1554/2000
1/1 - 0s - loss: 9.5803 - 11ms/epoch - 11ms/step
Epoch 1555/2000
1/1 - 0s - loss: 9.5673 - 5ms/epoch - 5ms/step
Epoch 1556/2000
1/1 - 0s - loss: 9.5543 - 6ms/epoch - 6ms/step
Epoch 1557/2000
1/1 - 0s - loss: 9.5414 - 10ms/epoch - 10ms/step
Epoch 1558/2000
1/1 - 0s - loss: 9.5284 - 5ms/epoch - 5ms/step
Epoch 1559/2000
1/1 - 0s - loss: 9.5155 - 9ms/epoch - 9ms/step
Epoch 1560/2000
1/1 - 0s - loss: 9.5025 - 8ms/epoch - 8ms/step
Epoch 1561/2000
1/1 - 0s - loss: 9.4896 - 8ms/epoch - 8ms/step
Epoch 1562/2000
1/1 - 0s - loss: 9.4768 - 14ms/epoch - 14ms/step


Epoch 1677/2000
1/1 - 0s - loss: 8.0411 - 4ms/epoch - 4ms/step
Epoch 1678/2000
1/1 - 0s - loss: 8.0291 - 7ms/epoch - 7ms/step
Epoch 1679/2000
1/1 - 0s - loss: 8.0171 - 6ms/epoch - 6ms/step
Epoch 1680/2000
1/1 - 0s - loss: 8.0051 - 3ms/epoch - 3ms/step
Epoch 1681/2000
1/1 - 0s - loss: 7.9931 - 4ms/epoch - 4ms/step
Epoch 1682/2000
1/1 - 0s - loss: 7.9811 - 7ms/epoch - 7ms/step
Epoch 1683/2000
1/1 - 0s - loss: 7.9691 - 8ms/epoch - 8ms/step
Epoch 1684/2000
1/1 - 0s - loss: 7.9571 - 7ms/epoch - 7ms/step
Epoch 1685/2000
1/1 - 0s - loss: 7.9451 - 4ms/epoch - 4ms/step
Epoch 1686/2000
1/1 - 0s - loss: 7.9333 - 4ms/epoch - 4ms/step
Epoch 1687/2000
1/1 - 0s - loss: 7.9213 - 4ms/epoch - 4ms/step
Epoch 1688/2000
1/1 - 0s - loss: 7.9093 - 6ms/epoch - 6ms/step
Epoch 1689/2000
1/1 - 0s - loss: 7.8974 - 4ms/epoch - 4ms/step
Epoch 1690/2000
1/1 - 0s - loss: 7.8855 - 5ms/epoch - 5ms/step
Epoch 1691/2000
1/1 - 0s - loss: 7.8737 - 3ms/epoch - 3ms/step
Epoch 1692/2000
1/1 - 0s - loss: 7.8618 - 5ms/epoch - 5

Epoch 1807/2000
1/1 - 0s - loss: 6.5527 - 12ms/epoch - 12ms/step
Epoch 1808/2000
1/1 - 0s - loss: 6.5419 - 13ms/epoch - 13ms/step
Epoch 1809/2000
1/1 - 0s - loss: 6.5311 - 9ms/epoch - 9ms/step
Epoch 1810/2000
1/1 - 0s - loss: 6.5203 - 7ms/epoch - 7ms/step
Epoch 1811/2000
1/1 - 0s - loss: 6.5094 - 5ms/epoch - 5ms/step
Epoch 1812/2000
1/1 - 0s - loss: 6.4986 - 4ms/epoch - 4ms/step
Epoch 1813/2000
1/1 - 0s - loss: 6.4878 - 4ms/epoch - 4ms/step
Epoch 1814/2000
1/1 - 0s - loss: 6.4770 - 7ms/epoch - 7ms/step
Epoch 1815/2000
1/1 - 0s - loss: 6.4662 - 4ms/epoch - 4ms/step
Epoch 1816/2000
1/1 - 0s - loss: 6.4554 - 5ms/epoch - 5ms/step
Epoch 1817/2000
1/1 - 0s - loss: 6.4446 - 6ms/epoch - 6ms/step
Epoch 1818/2000
1/1 - 0s - loss: 6.4339 - 7ms/epoch - 7ms/step
Epoch 1819/2000
1/1 - 0s - loss: 6.4231 - 4ms/epoch - 4ms/step
Epoch 1820/2000
1/1 - 0s - loss: 6.4123 - 8ms/epoch - 8ms/step
Epoch 1821/2000
1/1 - 0s - loss: 6.4016 - 4ms/epoch - 4ms/step
Epoch 1822/2000
1/1 - 0s - loss: 6.3909 - 7ms/epoch

Epoch 1937/2000
1/1 - 0s - loss: 5.2226 - 5ms/epoch - 5ms/step
Epoch 1938/2000
1/1 - 0s - loss: 5.2130 - 6ms/epoch - 6ms/step
Epoch 1939/2000
1/1 - 0s - loss: 5.2035 - 5ms/epoch - 5ms/step
Epoch 1940/2000
1/1 - 0s - loss: 5.1939 - 7ms/epoch - 7ms/step
Epoch 1941/2000
1/1 - 0s - loss: 5.1844 - 5ms/epoch - 5ms/step
Epoch 1942/2000
1/1 - 0s - loss: 5.1748 - 4ms/epoch - 4ms/step
Epoch 1943/2000
1/1 - 0s - loss: 5.1653 - 3ms/epoch - 3ms/step
Epoch 1944/2000
1/1 - 0s - loss: 5.1557 - 8ms/epoch - 8ms/step
Epoch 1945/2000
1/1 - 0s - loss: 5.1462 - 6ms/epoch - 6ms/step
Epoch 1946/2000
1/1 - 0s - loss: 5.1367 - 13ms/epoch - 13ms/step
Epoch 1947/2000
1/1 - 0s - loss: 5.1272 - 6ms/epoch - 6ms/step
Epoch 1948/2000
1/1 - 0s - loss: 5.1178 - 5ms/epoch - 5ms/step
Epoch 1949/2000
1/1 - 0s - loss: 5.1082 - 5ms/epoch - 5ms/step
Epoch 1950/2000
1/1 - 0s - loss: 5.0988 - 12ms/epoch - 12ms/step
Epoch 1951/2000
1/1 - 0s - loss: 5.0894 - 4ms/epoch - 4ms/step
Epoch 1952/2000
1/1 - 0s - loss: 5.0799 - 8ms/epoch

In [124]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_16 (Dense)            (None, 10)                40        
                                                                 
 dense_17 (Dense)            (None, 1)                 11        
                                                                 
Total params: 51
Trainable params: 51
Non-trainable params: 0
_________________________________________________________________


In [133]:

# demonstrate prediction

x_input = array( [622.0,606.0,508.0])

x_input

array([622., 606., 508.])

In [134]:

x_input = x_input.reshape(1 ,      #rows
                          3  #columns
                         ) 
x_input

array([[622., 606., 508.]])

In [136]:
x_input.flatten()

array([622., 606., 508.])

In [131]:

yhat = model.predict(x_input, verbose=2)

print(yhat)



1/1 - 0s - 15ms/epoch - 15ms/step
[[585.02936]]
